<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.3</Version>
    <Product>TalkPrompter</Product>
    <Company>Bosau Digital LLC</Company>
    <Copyright>Copyright (c) 2026 Bosau Digital LLC</Copyright>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
