<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Teleprompter.Core\Teleprompter.Core.csproj" />
    <ProjectReference Include="..\..\src\Teleprompter.Audio\Teleprompter.Audio.csproj" />
    <ProjectReference Include="..\..\src\Teleprompter.Speech\Teleprompter.Speech.csproj" />
  </ItemGroup>

</Project>
